use_frameworks!

target 'ViewComposer_Example' do
  pod 'ViewComposer', :path => '../'

  target 'ViewComposer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
